version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: booking-postgres-test
    env_file:
      - .env_test
    ports:
      - "${POSTGRES_PORT}:5432"

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - .env_test
    command: [ "server", "--console-address", ":9001", "/data" ]