"""empty message

Revision ID: 7090228a39e4
Revises: d7385031491b
Create Date: 2025-11-01 15:32:33.394932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7090228a39e4'
down_revision: Union[str, None] = 'd7385031491b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hotels', ['title'])
    op.drop_constraint(op.f('rooms_hotel_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_hotel_id_fkey'), 'rooms', 'hotels', ['hotel_id'], ['id'])
    op.drop_constraint(None, 'hotels', type_='unique')
    # ### end Alembic commands ###
