"""empty message

Revision ID: 9388071531cb
Revises: 7090228a39e4
Create Date: 2025-11-01 15:36:22.544907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9388071531cb'
down_revision: Union[str, None] = '7090228a39e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('facilities_rooms_rooms_id_fkey'), 'facilities_rooms', type_='foreignkey')
    op.drop_constraint(op.f('facilities_rooms_facilities_id_fkey'), 'facilities_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'facilities_rooms', 'facilities', ['facilities_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'facilities_rooms', 'rooms', ['rooms_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facilities_rooms', type_='foreignkey')
    op.drop_constraint(None, 'facilities_rooms', type_='foreignkey')
    op.create_foreign_key(op.f('facilities_rooms_facilities_id_fkey'), 'facilities_rooms', 'facilities', ['facilities_id'], ['id'])
    op.create_foreign_key(op.f('facilities_rooms_rooms_id_fkey'), 'facilities_rooms', 'rooms', ['rooms_id'], ['id'])
    # ### end Alembic commands ###
